# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'QSC_Swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QSC_Swift

pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON', '~> 3.1.3'
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJExtension'
pod 'SDWebImage'

  # pod 'ShareSDK3'
  # pod 'MOBFoundation'
  # pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
  # pod 'ShareSDK3/ShareSDKPlatforms/QQ'
  # pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

end